# Generated by Django 5.2.8 on 2025-11-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Costco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
