# Generated by Django 5.2.7 on 2025-11-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Costco', '0003_categoria_empleado_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='membresia',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Executive', 'Executive')], default='Gold', max_length=20),
        ),
    ]
